export enum OSStatus {
  PENDENTE = 'Pendente',
  EM_ANALISE = 'Em Análise',
  APROVADO = 'Aprovado',
  EM_ANDAMENTO = 'Em Andamento',
  CONCLUIDO = 'Concluído',
  CANCELADO = 'Cancelado'
}

export enum TransactionType {
  INCOME = 'Receita',
  EXPENSE = 'Despesa'
}

export interface Customer {
  id: string;
  name: string;
  phone: string;
  email: string;
  address: string;
}

export interface Product {
  id: string;
  name: string;
  price: number;
  cost: number;
  stock: number;
  category: string;
}

export interface ServiceOrder {
  id: string;
  customerId: string;
  customerName: string; // Denormalized for simpler display
  device: string;
  description: string;
  aiDiagnosis?: string; // Generated by Gemini
  status: OSStatus;
  priority: 'Baixa' | 'Média' | 'Alta';
  createdAt: string;
  totalValue: number;
  technicalNotes?: string;
}

export interface Transaction {
  id: string;
  description: string;
  amount: number;
  type: TransactionType;
  date: string;
  category: string;
}

export interface CartItem extends Product {
  quantity: number;
}

export interface SystemSettings {
  companyName: string;
  cnpj: string;
  phone: string;
  email: string;
  address: string;
  enableNotifications: boolean;
  enableSound: boolean;
}